//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active_LPN_Pick
    {
        public string User_Name { get; set; }
        public int Position { get; set; }
        public string Equipment_Type { get; set; }
        public string Conveyance_Type { get; set; }
        public string LPN { get; set; }
        public string Container_ID { get; set; }
    }
}
